title: SAFE Network apps
description: A directory of apps that are compatible with the SAFE Network
url: "https://apps.safenetwork.org"

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - Makefile

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed

permalink: /:title/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
